# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmdText = QtWidgets.QTextEdit(self.centralwidget)
        self.cmdText.setGeometry(QtCore.QRect(300, 380, 671, 351))
        self.cmdText.setObjectName("cmdText")
        self.cmdText.setReadOnly(True)
        self.portButton = QtWidgets.QRadioButton(self.centralwidget)
        self.portButton.setGeometry(QtCore.QRect(20, 380, 115, 19))
        self.portButton.setObjectName("portButton")
        self.pasvButton = QtWidgets.QRadioButton(self.centralwidget)
        self.pasvButton.setGeometry(QtCore.QRect(150, 380, 115, 19))
        self.pasvButton.setObjectName("pasvButton")
        self.fileTable = QtWidgets.QTableWidget(self.centralwidget)
        self.fileTable.setGeometry(QtCore.QRect(20, 70, 951, 291))
        self.fileTable.setObjectName("fileTable")
        self.fileTable.setColumnCount(6)
        self.fileTable.setRowCount(0)
        self.fileTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileTable.setHorizontalHeaderLabels([u'文件名',u'类型', u'大小',u'修改时间',u'权限',u'拥有者'])
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 951, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.IPInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.IPInput.setObjectName("IPInput")
        self.horizontalLayout.addWidget(self.IPInput)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.portInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.portInput.setObjectName("portInput")
        self.horizontalLayout.addWidget(self.portInput)
        self.connectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.usernameInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.horizontalLayout.addWidget(self.usernameInput)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.passwordInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordInput.setObjectName("passwordInput")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout.addWidget(self.passwordInput)
        self.loginButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 410, 261, 321))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.QUITButton = QtWidgets.QPushButton(self.widget)
        self.QUITButton.setObjectName("QUITButton")
        self.gridLayout_2.addWidget(self.QUITButton, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SYSTButton = QtWidgets.QPushButton(self.widget)
        self.SYSTButton.setObjectName("SYSTButton")
        self.gridLayout.addWidget(self.SYSTButton, 0, 0, 1, 1)
        self.MKDButton = QtWidgets.QPushButton(self.widget)
        self.MKDButton.setObjectName("MKDButton")
        self.gridLayout.addWidget(self.MKDButton, 0, 1, 1, 1)
        self.TYPEButton = QtWidgets.QPushButton(self.widget)
        self.TYPEButton.setObjectName("TYPEButton")
        self.gridLayout.addWidget(self.TYPEButton, 1, 0, 1, 1)
        self.CWDButton = QtWidgets.QPushButton(self.widget)
        self.CWDButton.setObjectName("CWDButton")
        self.gridLayout.addWidget(self.CWDButton, 1, 1, 1, 1)
        self.LISTButton = QtWidgets.QPushButton(self.widget)
        self.LISTButton.setObjectName("LISTButton")
        self.gridLayout.addWidget(self.LISTButton, 2, 0, 1, 1)
        self.PWDButton = QtWidgets.QPushButton(self.widget)
        self.PWDButton.setObjectName("PWDButton")
        self.gridLayout.addWidget(self.PWDButton, 2, 1, 1, 1)
        self.STORButton = QtWidgets.QPushButton(self.widget)
        self.STORButton.setObjectName("STORButton")
        self.gridLayout.addWidget(self.STORButton, 3, 0, 1, 1)
        self.RMDButton = QtWidgets.QPushButton(self.widget)
        self.RMDButton.setObjectName("RMDButton")
        self.gridLayout.addWidget(self.RMDButton, 3, 1, 1, 1)
        self.RETRButton = QtWidgets.QPushButton(self.widget)
        self.RETRButton.setObjectName("RETRButton")
        self.gridLayout.addWidget(self.RETRButton, 4, 0, 1, 1)
        self.MVButton = QtWidgets.QPushButton(self.widget)
        self.MVButton.setObjectName("MVButton")
        self.gridLayout.addWidget(self.MVButton, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP客户端"))
        self.portButton.setText(_translate("MainWindow", "PORT"))
        self.pasvButton.setText(_translate("MainWindow", "PASV"))
        self.label.setText(_translate("MainWindow", "IP/域名"))
        self.label_2.setText(_translate("MainWindow", "端口"))
        self.connectButton.setText(_translate("MainWindow", "连接"))
        self.label_3.setText(_translate("MainWindow", "用户名"))
        self.label_4.setText(_translate("MainWindow", "密码"))
        self.loginButton.setText(_translate("MainWindow", "登录"))
        self.QUITButton.setText(_translate("MainWindow", "退出"))
        self.SYSTButton.setText(_translate("MainWindow", "查看系统信息"))
        self.MKDButton.setText(_translate("MainWindow", "新建目录"))
        self.TYPEButton.setText(_translate("MainWindow", "设置传输格式"))
        self.CWDButton.setText(_translate("MainWindow", "切换目录"))
        self.LISTButton.setText(_translate("MainWindow", "刷新文件列表"))
        self.PWDButton.setText(_translate("MainWindow", "当前目录"))
        self.STORButton.setText(_translate("MainWindow", "上传文件"))
        self.RMDButton.setText(_translate("MainWindow", "删除目录"))
        self.RETRButton.setText(_translate("MainWindow", "下载文件"))
        self.MVButton.setText(_translate("MainWindow", "移动文件"))

